spring:
  application:
    name: user-data
  output:
    ansi:
      enabled: always

server:
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:ssl/localhost.p12
    key-store-password: sslarun
    key-alias: localhost
  http2:
    enabled: true

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
  metrics:
    tags:
      application: user-data
db:
  postgresql:
    driver: postgresql
    host: localhost
    port: 5432
    user: arun
    password: arun
    database: mydata
    schema: mydata


