spring:
  application:
    name: "user-data"
  output:
    ansi:
      enabled: "always"

server:
  http2:
    enabled: "true"

logging:
  level:
    root: "debug"

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "metrics"
  metrics:
    tags:
      application: "user-data"
db:
  driver: "postgresql"
  host: "localhost"
  port: "5432"
  user: "arun"
  password: "arun"
  database: "mydata"
  schema: "mydata"


